from __future__ import annotations

AGENT_IDS = tuple(f"AG-{i:02d}" for i in range(1, 11))
OUTPUT_IDS = tuple(f"OUT-{i:02d}" for i in range(1, 18))
CANONICAL_TEST_FIRST = 1
CANONICAL_TEST_LAST = 132
RUNTIME_KNOWLEDGE_COUNT = 16

FORBIDDEN_GROOM_IDS = frozenset({"SVC-03-008", "CTRL-011", "CTRL-012", "CTRL-013"})

CORE_DECISION_ROLES = ("BEST_FIT", "ALTERNATIVE", "BOLDER")
OPTIONAL_EXPLORE_LIMIT = 3
MAX_ACTIVE_LOOKS = 6

EVIDENCE_CLASSES = (
    "KNOWN",
    "OBSERVED",
    "USER_REPORTED",
    "INFERRED",
    "UNKNOWN",
    "REQUIRES_PROFESSIONAL_CHECK",
)

SAFETY_TIERS = ("S0", "S1", "S2", "S3")
SERVICE_DECISIONS = ("PROCEED", "MODIFY", "CHECK_FIRST", "DEFER", "STOP", "UNRESOLVED")

NON_NEGOTIABLE_RUNTIME_RULES = (
    "ONE_CANONICAL_TRUTH_STATE",
    "ANALYSIS_BEFORE_RANKED_RECOMMENDATION",
    "FILTER_INVALID_CANDIDATES_BEFORE_RANKING",
    "NO_FILLER_RECOMMENDATIONS",
    "CLIENT_SELECTION_NE_SPECIALIST_VALIDATION",
    "PREVIEW_NE_FEASIBILITY_OR_SAFETY_PROOF",
    "PROVIDER_OUTPUT_QUARANTINE_BEFORE_VISUAL_QA",
    "SOURCE_REALITY_CONSTRAINS_PREVIEW",
    "SAFETY_STATE_SURVIVES_TO_SERVICE_DECISION",
    "COMMERCIAL_LOGIC_MUST_NOT_REORDER_CORE_RECOMMENDATION_QUALITY",
)
